services:
  pg:
    container_name: brevly-postgres
    image: bitnami/postgresql:latest
    ports:
      - $PORT:$PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./docker:/docker-entrypoint-initdb.d:ro