services:
  web:
    container_name: brevly-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - brevly-network

networks:
  brevly-network:
    driver: bridge
